build:
  image: phpunit/phpunit:$$PHPUNIT_VERSION
  commands:
    #- printf "\n" | pecl install imagick
    - apt-get update
    - apt-get install -y libmagickwand-dev --no-install-recommends
    - rm -rf /var/lib/apt/lists/*
    - pecl install imagick
    - docker-php-ext-enable imagick
    #- echo "extension=imagick.so" >> /usr/local/etc/php.ini
    - phpunit Test test/unit/test.php

matrix:
  PHPUNIT_VERSION:
    - 4.8.5
    - 4.7.7
    - 4.6.10