build:
  image: phpunit/phpunit:$$PHPUNIT_VERSION
  commands:
    #- printf "\n" | pecl install imagick
    - ls /usr/local/etc/php/conf.d
    - apt-get update
    - apt-get install php-pear
    - apt-get install php5-dev imagemagick libmagickwand-dev
    - pecl install imagick
    - apt-get install php5-imagick
    #- echo "extension=imagick.so" >> /usr/local/etc/php.ini
    - phpunit Test test/unit/test.php

matrix:
  PHPUNIT_VERSION:
    - 4.8.5
    - 4.7.7
    - 4.6.10