build:
  image: phpunit/phpunit:$$PHPUNIT_VERSION
  commands:
    - printf "\n" | pecl install imagick
    - echo "extension=imagick.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - phpunit Test test/unit/test.php

matrix:
  PHPUNIT_VERSION:
    - 4.8.5
    - 4.7.7
    - 4.6.10