language: php
sudo: required
before_script:
  - printf "\n" | pecl install imagick
  - echo "extension=imagick.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
script: phpunit Test test/unit/test.php